import type { PictureDto } from '../../../shared/models/Picture';

const PICTURES: PictureDto[] = [
    {
        id: 5,
        url: "https://res.cloudinary.com/urbancore/image/upload/v1778750333/wwmd21mnx029mblyzqac.jpg",
        title: "Aston Martin Vantage",
        category: "Motorsport",
        description: "Lead car through the chicane at full attack, the Vantage AMR digging deep into ELMS territory.",
        isFeatured: true,
        cameraSettings: {
            focalLength: 400,
            shutterSpeed: 2500,
            aperture: "f/2.8",
            iso: 800,
            cameraBody: "Sony A9 III",
            lens: "FE 400mm f/2.8 GM",
        },
    },
    {
        id: 6,
        url: "https://res.cloudinary.com/urbancore/image/upload/v1778750327/jbnhgpscoknssr7pzze4.jpg",
        title: "Turn 10 Apex",
        category: "Motorsport",
        description: "Lead group hitting the apex of Turn 10, full lean, born on the limit.",
        isFeatured: true,
        cameraSettings: {
            focalLength: 150,
            shutterSpeed: 1600,
            aperture: "f/4",
            iso: 1600,
            cameraBody: "Sony A9 III",
            lens: "FE 70-200mm f/2.8 GM II",
        },
    },
    {
        id: 7,
        url: "https://res.cloudinary.com/urbancore/image/upload/v1778750322/e6ney7qsj0gixcqaz1hl.jpg",
        title: "Pit Lane Exit",
        category: "Motorsport",
        description: "GT3 machinery spilling out of the pit lane during a mid-race service window.",
        isFeatured: true,
        cameraSettings: {
            focalLength: 28,
            shutterSpeed: 400,
            aperture: "f/5.6",
            iso: 3200,
            cameraBody: "Sony A9 III",
            lens: "FE 24-70mm f/2.8 GM II",
        },
    },
    {
        id: 8,
        url: "https://res.cloudinary.com/urbancore/image/upload/v1778750319/cbmfyqmlycujwibtwhqd.jpg",
        title: "Brake Marker",
        category: "Motorsport",
        description: "Heavy braking into the hairpin, carbon dust catching the late afternoon sun.",
        isFeatured: true,
        cameraSettings: {
            focalLength: 200,
            shutterSpeed: 1250,
            aperture: "f/2.8",
            iso: 640,
            cameraBody: "Sony A9 III",
            lens: "FE 70-200mm f/2.8 GM II",
        },
    },
    {
        id: 9,
        url: "https://res.cloudinary.com/urbancore/image/upload/v1778750333/wwmd21mnx029mblyzqac.jpg",
        title: "Flat Out",
        category: "Motorsport",
        description: "Full throttle on the back straight, the 4.0-litre V8 singing at 7,200 rpm.",
        isFeatured: false,
        cameraSettings: {
            focalLength: 400,
            shutterSpeed: 2000,
            aperture: "f/2.8",
            iso: 800,
            cameraBody: "Sony A9 III",
            lens: "FE 400mm f/2.8 GM",
        },
    },
    {
        id: 11,
        url: "https://res.cloudinary.com/urbancore/image/upload/v1778750327/jbnhgpscoknssr7pzze4.jpg",
        title: "Kerb Strike",
        category: "Motorsport",
        description: "A deliberate stab at the inside kerb, suspension loaded to its absolute limit.",
        isFeatured: false,
        cameraSettings: {
            focalLength: 155,
            shutterSpeed: 600,
            aperture: "f/6.3",
            iso: 2000,
            cameraBody: "Sony A9 III",
            lens: "FE 200-600mm f/5.6-6.3 G",
        },
    },
    {
        id: 12,
        url: "https://res.cloudinary.com/urbancore/image/upload/v1778750322/e6ney7qsj0gixcqaz1hl.jpg",
        title: "Night Pursuit",
        category: "Motorsport",
        description: "Headlights carving the circuit in the dying minutes of a six-hour endurance battle.",
        isFeatured: false,
        cameraSettings: {
            focalLength: 200,
            shutterSpeed: 800,
            aperture: "f/4",
            iso: 4000,
            cameraBody: "Sony A9 III",
            lens: "FE 70-200mm f/2.8 GM II",
        },
    },
    {
        id: 14,
        url: "https://res.cloudinary.com/urbancore/image/upload/v1778750319/cbmfyqmlycujwibtwhqd.jpg",
        title: "Long Range",
        category: "Motorsport",
        description: "Shot from the far side of the circuit, compression revealing the density of a mid-pack battle.",
        isFeatured: false,
        cameraSettings: {
            focalLength: 600,
            shutterSpeed: 2000,
            aperture: "f/6.3",
            iso: 640,
            cameraBody: "Sony A9 III",
            lens: "FE 200-600mm f/5.6-6.3 G",
        },
    },
];

export function usePictures(): PictureDto[] {
    return PICTURES;
}
